import type {Metadata} from "next";
import {Roboto_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import {cn} from "@/lib/utils";
import {NextFont} from "next/dist/compiled/@next/font";
import {AppSidebar} from "@/components/layout/app-sidebar"
import {Separator} from "@/components/ui/separator"
import {SidebarInset, SidebarProvider, SidebarTrigger,} from "@/components/ui/sidebar"

const robotoMono: NextFont = Roboto_Mono({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Hydroponic",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn(robotoMono.className, 'min-h-screen')} suppressHydrationWarning>
        <SidebarProvider>
            <AppSidebar/>
            <SidebarInset>
                <header
                    className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                    <div className="flex items-center gap-2 px-4">
                        <SidebarTrigger className="-ml-1"/>
                        <Separator orientation="vertical" className="mr-2 h-4"/>
                    </div>
                </header>
                <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                    {children}
                </div>
            </SidebarInset>
        </SidebarProvider>
        </body>
        </html>
    );
}
